version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["sh", "-c", "php artisan optimize &&  php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000"]
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000" # Проброс порта для Octane
    environment:
      WWWUSER: '${WWWUSER}'
    depends_on:
      - pgsql
      - memcached
      - meilisearch
      - redis
    networks:
      - app-network
  pgsql:
    image: 'postgres:17'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
      - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf # Путь к конфигурации Nginx
      - ./public:/var/www/html # Путь к папке с публичными файлами, если это Laravel
      - ./docker/nginx.crt:/etc/nginx/ssl/nginx.crt  # Путь к SSL-сертификату
      - ./docker/nginx.key:/etc/nginx/ssl/nginx.key  # Путь к приватному ключу
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
  memcached:
    image: 'memcached:alpine'
    ports:
      - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
    networks:
      - app-network
  meilisearch:
    image: getmeili/meilisearch:v1.11.3
    container_name: meilisearch
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped
    networks:
      - app-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgsql:
    driver: local
  meili_data:
    driver: local
  redis-data:
    driver: local

